server:
  port: 8088
  
spring:
  output.ansi.enabled: ALWAYS
  datasource:
    url: "jdbc:postgresql://localhost:5435/tasksBase"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      default-schema: tasks_schema
      ddl-auto: update # none
    defer-datasource-initialization: true
  show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
  endpoint:
    health:
      show-details: always
  
